import "./globals.scss";
import { Space_Grotesk } from "next/font/google";
import Providers from "./providers";

const spaceGrotesk = Space_Grotesk({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--space-grotesk",
});

export const metadata = {
    title: "Arcatec React/Next Js Template",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${spaceGrotesk.variable}`}>
            <body className="">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
